# Generated by Django 4.2.7 on 2023-11-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Blog',
        ),
    ]
